// Generated by https://quicktype.io

using System;
using System.Collections.Generic;

namespace QuickType.VotersCard
{
    // Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse); 
    public class ReadResult
    {
        public int page { get; set; }
        public double angle { get; set; }
        public int width { get; set; }
        public int height { get; set; }
        public string unit { get; set; }
    }

    public class PageResult
    {
        public int page { get; set; }
        public List<object> tables { get; set; }
    }

    public class DateOfBirth
    {
        public string type { get; set; }
        public string valueString { get; set; }
        public string text { get; set; }
        public int page { get; set; }
        public List<double> boundingBox { get; set; }
        public double confidence { get; set; }
    }

    public class Code
    {
        public string type { get; set; }
        public string valueString { get; set; }
        public string text { get; set; }
        public int page { get; set; }
        public List<double> boundingBox { get; set; }
        public double confidence { get; set; }
    }

    public class FullName
    {
        public string type { get; set; }
        public string valueString { get; set; }
        public string text { get; set; }
        public int page { get; set; }
        public List<double> boundingBox { get; set; }
        public double confidence { get; set; }
    }

    public class CardType
    {
        public string type { get; set; }
        public string valueString { get; set; }
        public string text { get; set; }
        public int page { get; set; }
        public List<double> boundingBox { get; set; }
        public double confidence { get; set; }
    }

    public class Occupation
    {
        public string type { get; set; }
        public string valueString { get; set; }
        public string text { get; set; }
        public int page { get; set; }
        public List<double> boundingBox { get; set; }
        public double confidence { get; set; }
    }

    public class Delim
    {
        public string type { get; set; }
        public string valueString { get; set; }
        public string text { get; set; }
        public int page { get; set; }
        public List<double> boundingBox { get; set; }
        public double confidence { get; set; }
    }

    public class Address
    {
        public string type { get; set; }
        public string valueString { get; set; }
        public string text { get; set; }
        public int page { get; set; }
        public List<double> boundingBox { get; set; }
        public double confidence { get; set; }
    }

    public class VoterCardNo
    {
        public string type { get; set; }
        public string valueString { get; set; }
        public string text { get; set; }
        public int page { get; set; }
        public List<double> boundingBox { get; set; }
        public double confidence { get; set; }
    }

    public class Fields
    {
        public DateOfBirth DateOfBirth { get; set; }
        public Code code { get; set; }
        public FullName FullName { get; set; }
        public CardType CardType { get; set; }
        public Occupation Occupation { get; set; }
        public Delim delim { get; set; }
        public Address Address { get; set; }
        public VoterCardNo VoterCardNo { get; set; }
        public object Sex { get; set; }
    }

    public class DocumentResult
    {
        public string docType { get; set; }
        public string modelId { get; set; }
        public List<int> pageRange { get; set; }
        public Fields fields { get; set; }
        public double docTypeConfidence { get; set; }
    }

    public class AnalyzeResult
    {
        public string version { get; set; }
        public List<ReadResult> readResults { get; set; }
        public List<PageResult> pageResults { get; set; }
        public List<DocumentResult> documentResults { get; set; }
        public List<object> errors { get; set; }
    }

    public class Root
    {
        public string status { get; set; }
        public DateTime createdDateTime { get; set; }
        public DateTime lastUpdatedDateTime { get; set; }
        public AnalyzeResult analyzeResult { get; set; }
    }


}
